# Generated by Django 4.2.4 on 2023-12-22 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('asignatura', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observacion', models.CharField(max_length=250, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminario_app.institucion')),
            ],
        ),
    ]
