# Generated by Django 4.2.4 on 2023-12-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='institucion',
            field=models.CharField(max_length=50),
        ),
    ]
